<?php

/**
 * @file
 * Contains alloy_file_browser.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_help().
 */
function alloy_file_browser_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the alloy_file_browser module.
    case 'help.page.alloy_file_browser':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Alloy file browser tweaks') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function alloy_file_browser_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id == 'entity_embed_dialog') {
    file_browser_attach_file_browser_to_form($form);
    $code = json_encode($form);
    \Drupal::logger('alloy_file_browser')->notice('@form',
        array(
            '@form' => $code,
        ));
  }
  if ($form_id == 'entity_browser_browse_files_modal_form') {
    $form['selection_display']['#prefix'] = '<div class="selected-display">';
    $form['selection_display']['#suffix'] = '</div>';
  }
}
